spring:
    
  config:
    import: ${IMPORT_CONFIG}
    
  h2:
    console:
      enabled: true
      
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
